"""Catalogue français de formulations biographiques normalisées.

Chaque fragment peut apparaître dans une question plus longue. Les variantes de personne,
de temps et de structure autour du fragment produisent plusieurs centaines de formulations.
"""

PROPERTY_PHRASES: dict[str, tuple[str, ...]] = {
    "DESCRIPTION": (
        "qui est",
        "qui etait",
        "presente moi",
        "parle moi de",
        "raconte moi sa vie",
        "resume sa vie",
        "sa biographie",
        "c est qui",
    ),
    "P19": (
        "ou est ne",
        "ou est nee",
        "lieu de naissance",
        "ville de naissance",
        "pays de naissance",
        "ne dans quelle ville",
        "nee dans quelle ville",
        "il vient d ou",
        "elle vient d ou",
        "il est ne ou",
        "elle est nee ou",
        "il est ne dans quelle ville",
        "elle est nee dans quelle ville",
        "il est ne dans quel pays",
        "elle est nee dans quel pays",
    ),
    "P569": (
        "quand est ne",
        "quand est nee",
        "date de naissance",
        "annee de naissance",
        "jour de naissance",
        "ne en quelle annee",
        "nee en quelle annee",
        "il est ne quand",
        "elle est nee quand",
        "ils sont nes quand",
        "elles sont nees quand",
        "quand sont ils nes",
        "quand sont elles nees",
        "ils sont nes en quelle annee",
        "elles sont nees en quelle annee",
    ),
    "P570": (
        "quand est mort",
        "quand est morte",
        "quand est decede",
        "quand est decedee",
        "date de deces",
        "annee de deces",
        "mort en quelle annee",
        "morte en quelle annee",
        "il est mort quand",
        "elle est morte quand",
        "ils sont morts quand",
        "sont ils morts",
    ),
    "P27": (
        "quelle nationalite",
        "sa nationalite",
        "de quelle nationalite",
        "de quel pays",
        "pays d origine",
        "ses origines",
        "il est de quel pays",
        "elle est de quel pays",
    ),
    "P106": (
        "quel metier",
        "quelle profession",
        "son metier",
        "sa profession",
        "que fait il dans la vie",
        "que fait elle dans la vie",
        "il travaille dans quoi",
        "elle travaille dans quoi",
        "activite professionnelle",
    ),
    "P69": (
        "quelles etudes",
        "ses etudes",
        "quelle universite",
        "quelle ecole",
        "ou a t il etudie",
        "ou a t elle etudie",
        "formation universitaire",
        "parcours scolaire",
        "diplome de quelle ecole",
    ),
    "P26": (
        "son mari",
        "sa femme",
        "son epoux",
        "son epouse",
        "son conjoint",
        "sa conjointe",
        "avec qui est il marie",
        "avec qui est elle mariee",
        "qui partage sa vie",
        "ses relations amoureuses",
        "combien de maris",
        "combien de femmes",
    ),
    "P40": (
        "ses enfants",
        "combien d enfants",
        "qui sont ses enfants",
        "a t il des enfants",
        "a t elle des enfants",
        "il a combien d enfants",
        "elle a combien d enfants",
        "noms de ses enfants",
        "ses fils et filles",
    ),
    "P166": (
        "quels prix",
        "quelles recompenses",
        "ses distinctions",
        "prix recus",
        "recompenses recues",
        "a t il gagne un prix",
        "a t elle gagne un prix",
        "a t il eu le nobel",
        "palmares",
    ),
    "P39": (
        "quelles fonctions",
        "quels postes",
        "ses fonctions",
        "ses mandats",
        "poste occupe",
        "fonction politique",
        "a t il ete president",
        "a t elle ete presidente",
        "responsabilites exercees",
    ),
    "P22": ("son pere", "qui est son pere", "nom de son pere", "identite du pere", "son papa"),
    "P25": ("sa mere", "qui est sa mere", "nom de sa mere", "identite de la mere", "sa maman"),
    "P3373": (
        "ses freres et soeurs",
        "sa fratrie",
        "a t il des freres",
        "a t elle des soeurs",
        "qui sont ses freres",
        "qui sont ses soeurs",
    ),
    "P108": (
        "son employeur",
        "pour qui travaille",
        "dans quelle entreprise",
        "quelle societe l emploie",
        "son entreprise",
        "ou travaille t il",
        "ou travaille t elle",
    ),
    "P551": (
        "ou habite",
        "ou vit il",
        "ou vit elle",
        "son lieu de residence",
        "sa residence",
        "dans quelle ville habite",
        "domicile actuel",
    ),
    "P140": (
        "quelle religion",
        "sa religion",
        "ses croyances religieuses",
        "est il croyant",
        "est elle croyante",
        "confession religieuse",
    ),
    "P102": (
        "quel parti politique",
        "son parti politique",
        "dans quel parti",
        "appartenance politique",
        "membre de quel parti",
    ),
    "P1412": (
        "quelles langues",
        "langues parlees",
        "quelle langue parle",
        "il parle quelles langues",
        "elle parle quelles langues",
        "ses langues",
    ),
    "P800": (
        "ses oeuvres",
        "oeuvres principales",
        "travaux connus",
        "livres les plus connus",
        "films les plus connus",
        "qu a t il ecrit",
        "qu a t elle ecrit",
    ),
    "P101": (
        "son domaine",
        "domaine d activite",
        "domaine de recherche",
        "sa specialite",
        "dans quel domaine",
        "discipline principale",
    ),
    "P136": (
        "quel genre musical",
        "son style musical",
        "genre artistique",
        "quel style de musique",
        "son genre artistique",
    ),
    "P1303": (
        "quel instrument",
        "son instrument",
        "de quel instrument joue",
        "instrument de musique",
        "il joue de quoi",
        "elle joue de quoi",
    ),
    "P2048": (
        "quelle taille",
        "combien mesure",
        "sa taille",
        "il mesure combien",
        "elle mesure combien",
        "quelle est sa hauteur",
    ),
    "P509": (
        "cause de sa mort",
        "cause du deces",
        "mort de quoi",
        "de quoi est il mort",
        "de quoi est elle morte",
        "comment est il mort",
        "comment est elle morte",
    ),
    "P119": (
        "ou est enterre",
        "ou est enterree",
        "lieu d inhumation",
        "ou se trouve sa tombe",
        "dans quel cimetiere",
        "lieu de sepulture",
    ),
    "P856": (
        "site officiel",
        "son site web",
        "adresse de son site",
        "site internet officiel",
        "quelle est son url",
    ),
}

# Variantes familières, inversées et conversationnelles. Ce second niveau reste séparé
# pour rendre les ajouts relisibles et éviter une liste monolithique.
EXTRA_PROPERTY_PHRASES: dict[str, tuple[str, ...]] = {
    "DESCRIPTION": (
        "tu sais qui est",
        "donne moi des infos sur",
        "c est quelle personne",
        "fais son portrait",
        "dis moi tout sur",
    ),
    "P19": (
        "dans quel endroit est ne",
        "elle est originaire d ou",
        "il est originaire d ou",
        "naissance dans quelle ville",
        "c est quoi son lieu de naissance",
        "il est ne a quel endroit",
        "elle est nee a quel endroit",
        "dans quelle ville est il ne",
        "dans quelle ville est elle nee",
        "dans quel pays est il ne",
        "dans quel pays est elle nee",
    ),
    "P569": (
        "c est quoi sa date de naissance",
        "il est ne quel jour",
        "elle est nee quel jour",
        "sa naissance date de quand",
        "donne son annee de naissance",
        "et ils sont nes quand",
        "et elles sont nees quand",
        "leurs dates de naissance",
    ),
    "P570": (
        "il est decede quand",
        "elle est decedee quand",
        "ils sont decedes quand",
        "quelle est sa date de mort",
        "donne son annee de deces",
        "a quelle date est il mort",
    ),
    "P27": (
        "il est de quelle origine",
        "elle est de quelle origine",
        "quelle est son origine",
        "il vient de quel pays",
        "elle vient de quel pays",
        "c est quoi sa citoyennete",
    ),
    "P106": (
        "il fait quoi",
        "elle fait quoi",
        "il bosse dans quoi",
        "elle bosse dans quoi",
        "c est quoi son travail",
        "quel est son boulot",
        "comment gagne t il sa vie",
    ),
    "P69": (
        "elle a etudie ou",
        "il a etudie ou",
        "elle a fait quelle ecole",
        "il a fait quelle fac",
        "quel est son parcours academique",
        "elle a quel diplome",
    ),
    "P26": (
        "il est avec qui",
        "elle est avec qui",
        "qui est son partenaire",
        "qui est sa partenaire",
        "avec qui vit elle",
        "avec qui vit il",
        "elle est en couple avec qui",
    ),
    "P40": (
        "elle a des gosses",
        "il a des gosses",
        "combien de gosses",
        "elle est mere de qui",
        "il est pere de qui",
        "qui sont leurs enfants",
        "ils ont combien d enfants",
    ),
    "P166": (
        "elle a gagne quoi",
        "il a gagne quoi",
        "quels trophees",
        "quelles medailles",
        "quels honneurs",
        "elle a ete recompensee pour quoi",
    ),
    "P39": (
        "quel role officiel",
        "quel poste politique",
        "il a dirige quoi",
        "elle a dirige quoi",
        "quelles responsabilites",
        "quelle fonction occupait il",
    ),
    "P22": (
        "comment s appelle son pere",
        "c est qui son papa",
        "quel est le pere",
        "pere biologique",
        "qui etait son pere",
    ),
    "P25": (
        "comment s appelle sa mere",
        "c est qui sa maman",
        "quelle est la mere",
        "mere biologique",
        "qui etait sa mere",
    ),
    "P3373": (
        "il a des freres et soeurs",
        "elle a des freres et soeurs",
        "combien de freres et soeurs",
        "qui est dans sa fratrie",
        "ses soeurs",
        "ses freres",
    ),
    "P108": (
        "elle bosse pour qui",
        "il bosse pour qui",
        "qui l emploie",
        "dans quelle boite",
        "quelle boite l emploie",
        "son lieu de travail",
    ),
    "P551": (
        "elle vit ou",
        "il vit ou",
        "elle reside ou",
        "il reside ou",
        "c est quoi son adresse",
        "dans quel pays habite",
        "ou se trouve son domicile",
    ),
    "P140": (
        "elle croit en quoi",
        "il croit en quoi",
        "de quelle confession",
        "quelle est sa foi",
        "ses convictions religieuses",
        "il pratique quelle religion",
    ),
    "P102": (
        "elle est dans quel parti",
        "il est dans quel parti",
        "quelle formation politique",
        "son mouvement politique",
        "il milite ou",
        "elle milite ou",
    ),
    "P1412": (
        "elle parle quoi",
        "il parle quoi",
        "elle sait parler quelles langues",
        "il sait parler quelles langues",
        "langues maitrisees",
        "elle est bilingue en quoi",
    ),
    "P800": (
        "elle est connue pour quelle oeuvre",
        "il est connu pour quelle oeuvre",
        "quels sont ses travaux",
        "ses creations connues",
        "quels livres a t il ecrits",
        "dans quels films a t elle joue",
    ),
    "P101": (
        "elle est experte en quoi",
        "il est expert en quoi",
        "quel est son secteur",
        "elle travaille dans quel domaine",
        "son champ de recherche",
        "sa discipline",
    ),
    "P136": (
        "elle fait quel style",
        "il fait quel style",
        "quel type de musique",
        "courant artistique",
        "son univers musical",
        "quel est son genre de musique",
    ),
    "P1303": (
        "elle joue de quoi",
        "il joue de quoi",
        "elle pratique quel instrument",
        "il pratique quel instrument",
        "quels instruments maitrise t il",
        "instrument principal",
    ),
    "P2048": (
        "elle fait quelle taille",
        "il fait quelle taille",
        "combien fait il",
        "combien fait elle",
        "sa hauteur",
        "quelle est sa stature",
    ),
    "P509": (
        "pourquoi est il mort",
        "pourquoi est elle morte",
        "qu est ce qui a cause sa mort",
        "raison de son deces",
        "comment est survenu son deces",
        "il est mort a cause de quoi",
    ),
    "P119": (
        "elle repose ou",
        "il repose ou",
        "ou est sa tombe",
        "dans quel lieu est il enterre",
        "dans quel lieu est elle enterree",
        "quelle est sa sepulture",
    ),
    "P856": (
        "donne son site",
        "c est quoi son site",
        "lien de son site",
        "son url officielle",
        "page web officielle",
        "ou trouver son site officiel",
    ),
}

PROPERTY_PHRASES = {
    property_id: phrases + EXTRA_PROPERTY_PHRASES.get(property_id, ())
    for property_id, phrases in PROPERTY_PHRASES.items()
}
