"""Catalogue français de formulations biographiques normalisées.

Chaque fragment peut apparaître dans une question plus longue. Les variantes de personne,
de temps et de structure autour du fragment produisent plusieurs centaines de formulations.
"""

PROPERTY_PHRASES: dict[str, tuple[str, ...]] = {
    "DESCRIPTION": (
        "qui est",
        "qui etait",
        "presente moi",
        "parle moi de",
        "raconte moi sa vie",
        "resume sa vie",
        "sa biographie",
        "c est qui",
    ),
    "P19": (
        "ou est ne",
        "ou est nee",
        "lieu de naissance",
        "ville de naissance",
        "pays de naissance",
        "ne dans quelle ville",
        "nee dans quelle ville",
        "il vient d ou",
        "elle vient d ou",
    ),
    "P569": (
        "quand est ne",
        "quand est nee",
        "date de naissance",
        "annee de naissance",
        "jour de naissance",
        "ne en quelle annee",
        "nee en quelle annee",
        "il est ne quand",
        "elle est nee quand",
    ),
    "P570": (
        "quand est mort",
        "quand est morte",
        "quand est decede",
        "quand est decedee",
        "date de deces",
        "annee de deces",
        "mort en quelle annee",
        "morte en quelle annee",
        "il est mort quand",
        "elle est morte quand",
        "ils sont morts quand",
        "sont ils morts",
    ),
    "P27": (
        "quelle nationalite",
        "sa nationalite",
        "de quelle nationalite",
        "de quel pays",
        "pays d origine",
        "ses origines",
        "il est de quel pays",
        "elle est de quel pays",
    ),
    "P106": (
        "quel metier",
        "quelle profession",
        "son metier",
        "sa profession",
        "que fait il dans la vie",
        "que fait elle dans la vie",
        "il travaille dans quoi",
        "elle travaille dans quoi",
        "activite professionnelle",
    ),
    "P69": (
        "quelles etudes",
        "ses etudes",
        "quelle universite",
        "quelle ecole",
        "ou a t il etudie",
        "ou a t elle etudie",
        "formation universitaire",
        "parcours scolaire",
        "diplome de quelle ecole",
    ),
    "P26": (
        "son mari",
        "sa femme",
        "son epoux",
        "son epouse",
        "son conjoint",
        "sa conjointe",
        "avec qui est il marie",
        "avec qui est elle mariee",
        "qui partage sa vie",
        "ses relations amoureuses",
        "combien de maris",
        "combien de femmes",
    ),
    "P40": (
        "ses enfants",
        "combien d enfants",
        "qui sont ses enfants",
        "a t il des enfants",
        "a t elle des enfants",
        "il a combien d enfants",
        "elle a combien d enfants",
        "noms de ses enfants",
        "ses fils et filles",
    ),
    "P166": (
        "quels prix",
        "quelles recompenses",
        "ses distinctions",
        "prix recus",
        "recompenses recues",
        "a t il gagne un prix",
        "a t elle gagne un prix",
        "a t il eu le nobel",
        "palmares",
    ),
    "P39": (
        "quelles fonctions",
        "quels postes",
        "ses fonctions",
        "ses mandats",
        "poste occupe",
        "fonction politique",
        "a t il ete president",
        "a t elle ete presidente",
        "responsabilites exercees",
    ),
    "P22": ("son pere", "qui est son pere", "nom de son pere", "identite du pere", "son papa"),
    "P25": ("sa mere", "qui est sa mere", "nom de sa mere", "identite de la mere", "sa maman"),
    "P3373": (
        "ses freres et soeurs",
        "sa fratrie",
        "a t il des freres",
        "a t elle des soeurs",
        "qui sont ses freres",
        "qui sont ses soeurs",
    ),
    "P108": (
        "son employeur",
        "pour qui travaille",
        "dans quelle entreprise",
        "quelle societe l emploie",
        "son entreprise",
        "ou travaille t il",
        "ou travaille t elle",
    ),
    "P551": (
        "ou habite",
        "ou vit il",
        "ou vit elle",
        "son lieu de residence",
        "sa residence",
        "dans quelle ville habite",
        "domicile actuel",
    ),
    "P140": (
        "quelle religion",
        "sa religion",
        "ses croyances religieuses",
        "est il croyant",
        "est elle croyante",
        "confession religieuse",
    ),
    "P102": (
        "quel parti politique",
        "son parti politique",
        "dans quel parti",
        "appartenance politique",
        "membre de quel parti",
    ),
    "P1412": (
        "quelles langues",
        "langues parlees",
        "quelle langue parle",
        "il parle quelles langues",
        "elle parle quelles langues",
        "ses langues",
    ),
    "P800": (
        "ses oeuvres",
        "oeuvres principales",
        "travaux connus",
        "livres les plus connus",
        "films les plus connus",
        "qu a t il ecrit",
        "qu a t elle ecrit",
    ),
    "P101": (
        "son domaine",
        "domaine d activite",
        "domaine de recherche",
        "sa specialite",
        "dans quel domaine",
        "discipline principale",
    ),
    "P136": (
        "quel genre musical",
        "son style musical",
        "genre artistique",
        "quel style de musique",
        "son genre artistique",
    ),
    "P1303": (
        "quel instrument",
        "son instrument",
        "de quel instrument joue",
        "instrument de musique",
        "il joue de quoi",
        "elle joue de quoi",
    ),
    "P2048": (
        "quelle taille",
        "combien mesure",
        "sa taille",
        "il mesure combien",
        "elle mesure combien",
        "quelle est sa hauteur",
    ),
    "P509": (
        "cause de sa mort",
        "cause du deces",
        "mort de quoi",
        "de quoi est il mort",
        "de quoi est elle morte",
        "comment est il mort",
        "comment est elle morte",
    ),
    "P119": (
        "ou est enterre",
        "ou est enterree",
        "lieu d inhumation",
        "ou se trouve sa tombe",
        "dans quel cimetiere",
        "lieu de sepulture",
    ),
    "P856": (
        "site officiel",
        "son site web",
        "adresse de son site",
        "site internet officiel",
        "quelle est son url",
    ),
}
